# Generated by Django 3.1.4 on 2021-11-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('model', models.CharField(max_length=100)),
                ('regdno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fuel', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('booked', models.BooleanField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station')),
            ],
        ),
    ]
